import { TextResponse } from '.';

export const DEFAULT_RESPONSE_RU: TextResponse = {
  text: 'Крупнейшими из всех животных, живущих сейчас на нашей планете, являются киты. Длина рекордсмена - синего или голубого кита - составляет 25 м, а масса - до 150 т.',
  lang: 'ru',
};

export const DEFAULT_RESPONSE: TextResponse = {
  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam efficitur rutrum efficitur. Phasellus sit amet mauris pellentesque, viverra felis vitae.',
  lang: 'en',
};

export const KEYS_EN: Record<string, string> = {
  0: 'Digit0',
  1: 'Digit1',
  2: 'Digit2',
  3: 'Digit3',
  4: 'Digit4',
  5: 'Digit5',
  6: 'Digit6',
  7: 'Digit7',
  8: 'Digit8',
  9: 'Digit9',
  '§': 'Backquote',
  '-': 'Minus',
  '=': 'Equal',
  ']': 'BracketRight',
  '[': 'BracketLeft',
  p: 'KeyP',
  o: 'KeyO',
  i: 'KeyI',
  u: 'KeyU',
  y: 'KeyY',
  t: 'KeyT',
  r: 'KeyR',
  e: 'KeyE',
  w: 'KeyW',
  q: 'KeyQ',
  a: 'KeyA',
  s: 'KeyS',
  d: 'KeyD',
  f: 'KeyF',
  g: 'KeyG',
  h: 'KeyH',
  j: 'KeyJ',
  k: 'KeyK',
  l: 'KeyL',
  ';': 'Semicolon',
  "'": 'Quote',
  '\\': 'Backslash',
  '/': 'Slash',
  '.': 'Period',
  ',': 'Comma',
  m: 'KeyM',
  n: 'KeyN',
  b: 'KeyB',
  v: 'KeyV',
  c: 'KeyC',
  x: 'KeyX',
  z: 'KeyZ',
  '`': 'IntlBackslash',
  ' ': 'Space',
};

export const KEYS_EN_SHIFT: Record<string, string> = {
  '±': 'Backquote',
  '!': 'Digit1',
  '@': 'Digit2',
  '#': 'Digit3',
  $: 'Digit4',
  '%': 'Digit5',
  '^': 'Digit6',
  '&': 'Digit7',
  '*': 'Digit8',
  '(': 'Digit9',
  ')': 'Digit0',
  _: 'Minus',
  '+': 'Equal',
  '}': 'BracketRight',
  '{': 'BracketLeft',
  P: 'KeyP',
  O: 'KeyO',
  I: 'KeyI',
  U: 'KeyU',
  Y: 'KeyY',
  T: 'KeyT',
  R: 'KeyR',
  E: 'KeyE',
  W: 'KeyW',
  Q: 'KeyQ',
  A: 'KeyA',
  S: 'KeyS',
  D: 'KeyD',
  F: 'KeyF',
  G: 'KeyG',
  H: 'KeyH',
  J: 'KeyJ',
  K: 'KeyK',
  L: 'KeyL',
  ':': 'Semicolon',
  '"': 'Quote',
  '|': 'Backslash',
  '?': 'Slash',
  '>': 'Period',
  '<': 'Comma',
  M: 'KeyM',
  N: 'KeyN',
  B: 'KeyB',
  V: 'KeyV',
  C: 'KeyC',
  X: 'KeyX',
  Z: 'KeyZ',
  '~': 'IntlBackslash',
};

export const KEYS_RU: Record<string, string> = {
  0: 'Digit0',
  1: 'Digit1',
  2: 'Digit2',
  3: 'Digit3',
  4: 'Digit4',
  5: 'Digit5',
  6: 'Digit6',
  7: 'Digit7',
  8: 'Digit8',
  9: 'Digit9',
  ё: 'Backquote',
  '-': 'Minus',
  '=': 'Equal',
  Backspace: 'Backspace',
  Enter: 'Enter',
  ъ: 'BracketRight',
  х: 'BracketLeft',
  з: 'KeyP',
  щ: 'KeyO',
  ш: 'KeyI',
  г: 'KeyU',
  н: 'KeyY',
  е: 'KeyT',
  к: 'KeyR',
  у: 'KeyE',
  ц: 'KeyW',
  й: 'KeyQ',
  ф: 'KeyA',
  ы: 'KeyS',
  в: 'KeyD',
  а: 'KeyF',
  п: 'KeyG',
  р: 'KeyH',
  о: 'KeyJ',
  л: 'KeyK',
  д: 'KeyL',
  ж: 'Semicolon',
  э: 'Quote',
  '\\': 'Backslash',
  '.': 'Slash',
  ю: 'Period',
  б: 'Comma',
  ь: 'KeyM',
  т: 'KeyN',
  и: 'KeyB',
  м: 'KeyV',
  с: 'KeyC',
  ч: 'KeyX',
  я: 'KeyZ',
  ']': 'IntlBackslash',
  ' ': 'Space',
};

export const KEYS_RU_SHIFT: Record<string, string> = {
  Ё: 'Backquote',
  '!': 'Digit1',
  '"': 'Digit2',
  '№': 'Digit3',
  ';': 'Digit4',
  '%': 'Digit5',
  ':': 'Digit6',
  '?': 'Digit7',
  '*': 'Digit8',
  '(': 'Digit9',
  ')': 'Digit0',
  _: 'Minus',
  '+': 'Equal',
  Ъ: 'BracketRight',
  Х: 'BracketLeft',
  З: 'KeyP',
  Щ: 'KeyO',
  Ш: 'KeyI',
  Г: 'KeyU',
  Н: 'KeyY',
  Е: 'KeyT',
  К: 'KeyR',
  У: 'KeyE',
  Ц: 'KeyW',
  Й: 'KeyQ',
  Ф: 'KeyA',
  Ы: 'KeyS',
  В: 'KeyD',
  А: 'KeyF',
  П: 'KeyG',
  Р: 'KeyH',
  О: 'KeyJ',
  Л: 'KeyK',
  Д: 'KeyL',
  Ж: 'Semicolon',
  Э: 'Quote',
  '/': 'Backslash',
  ',': 'Slash',
  Ю: 'Period',
  Б: 'Comma',
  Ь: 'KeyM',
  Т: 'KeyN',
  И: 'KeyB',
  М: 'KeyV',
  С: 'KeyC',
  Ч: 'KeyX',
  Я: 'KeyZ',
  '[': 'IntlBackslash',
};

export default { DEFAULT_RESPONSE_RU, DEFAULT_RESPONSE };
